clurz

diff --git a/despot b/despot
--- a/despot
+++ b/despot
@@ -117,7 +117,7 @@ esac
 # install process
 case "$PKG_LOCK" in
   install | i) 
-    echo "\n\e[92m->\e[0m checking dependencies"
+    echo "\n${GREEN}->${WHITE} checking dependencies"
     case "$(cat /etc/os-release)" in
       *debian*)
         echo "$DEB_DEPENDENCIES" | xargs apt-get install -y
@@ -126,15 +126,15 @@ case "$PKG_LOCK" in
 	echo "$RPM_DEPENDENCIES" | xargs dnf install -y
 	;;
     esac
-    echo "\e[92m->\e[0m done\n"
-    echo "\e[92m->\e[0m compiling: $PKG_TITLE"
+    echo "${GREEN}->${WHITE} done\n"
+    echo "${GREEN}->${WHITE} compiling: $PKG_TITLE"
     package_install && PKG_LOCK=0 &&
-    echo "\e[92m->\e[0m installed: $PKG_TITLE" || die 88 ;;
+    echo "${GREEN}->${WHITE} installed: $PKG_TITLE" || die 88 ;;
   uninstall | u) 
-    echo "-> uninstalling: \e[91m$PKG_TITLE\e[0m"
+    echo "${RED}->${WHITE} uninstalling: ${RED}$PKG_TITLE${WHITE}"
     package_uninstall &&
-    echo "-> uninstalled:  \e[91m$PKG_TITLE\e[0m" || \
-    echo "-> \e[91mbuild failed\e[0m: $PKG_TITLE"
+    echo "${RED}->${WHITE} uninstalled:  ${RED}$PKG_TITLE${WHITE}" || \
+    echo "${RED}->${WHITE} uninstall failed: ${RED}$PKG_TITLE${WHITE}"
     PKG_LOCK=1
     ;;
 esac
