Update despot

diff --git a/despot b/despot
--- a/despot
+++ b/despot
@@ -10,12 +10,21 @@ die() {
     1) echo "error: package not installed"; exit ;;
     2) echo "error: missing dependency $2"; exit ;;
     3) echo "error: no argument given"; exit ;;
+    4) echo "error: no dbuild available for $2"; exit ;;
     99) exit ;;
   esac
 }
 
 PKG_NAME="$2"
-test $1 && PKG_LOCK="$1" && . db/repo/{dream,nightmare}/$PKG_NAME.dbuild || PKG_LOCK="help"
+test $1 && PKG_LOCK="$1" || PKG_LOCK="help"
+case "$PKG_LOCK" in "install" | "uninstall")
+  live_repo=$(find db/repo -type f -name '*.dbuild' | grep -i $PKG_NAME | rev | cut -d / -f2 | rev)
+  test ! -e $live_repo || die 4 $PKG_NAME
+  echo -e "-> found \e[32m$PKG_NAME\e[0m in \e[33m$live_repo\e[0m"
+  echo -e "-> processing dbuild: \e[32m$PKG_NAME\e[0m\n"
+  . ./db/repo/${live_repo}/${PKG_NAME}.dbuild
+esac
+
 case "$PKG_LOCK" in
   "install") 
     echo -e "\e[32m[dependency management: START]\e[0m"
@@ -31,8 +40,10 @@ case "$PKG_LOCK" in
     package_uninstall
     echo -e "-> uninstalled:  \e[31m$PKG_TITLE\e[0m"
     ;;
-  "version" | "v") echo "despot ${DESPOT_VERSION}"; die 99 ;;
-  "help" | "h") cat << EOF
+  "version" | "v")
+    echo "despot ${DESPOT_VERSION}"; die 99 ;;
+  "help" | "h")
+    cat << EOF
 ./despot [cmd]
 
 commands:
@@ -41,7 +52,8 @@ install [pkg]   | install a package
 uninstall [pkg] | uninstall a package
 version         | show current version
 EOF
-  die 99 ;;
+    die 99
+    ;;
 esac
 
 unset PKG_TITLE PKG_AUTHOR PKG_VERSION package_remove sources_verify package_install
